### ISSUE TITLE
The HTML file..

### ISSUE THREAD

**Issue by Leonlit** [Hotsotse/Hang-man#1]
could you explain what is the use of the HTML file in this project....

**Comment by Elephant454** [comment]
The directory "Hang-man/doc/html" is the html version of the Doxygen documentation. Doxygen lets us generate graphs and other information explaining how the code works. The html and latex directories shouldn't be there, as the documentation should just be generated locally when someone wants it.

We might want to keep the Doxyfile, though. The project obviously isn't very big, but it might be fun to get some practice creating documentation.

Any concerns before we close this?

**Comment by Leonlit** [comment]
Oh thanks
