### ISSUE TITLE
Please grant access to ask for pushes. I added additional 164 countries to the code.

### ISSUE THREAD

**Issue by AleksandreLomadzeGabiani** [Hotsotse/Hang-man#2]
I added a bunch of countries to the code. PLS grant access to push,or do it yourself. I post zip here too.

I have also removed the (using namespace std::),because it can cause errors later when adding more files. so you would rather get it sorted early. Please run to check if all std::'s are added.

!! UPDATE - I tried removing the namespace,but it seems to mess up the code even further. 🗡  lulz I will just branch the version that has more countries with it and hope it works,as I am unable to properly compile this for some reason..

[main.zip](https://github.com/Hotsotse/Hang-man/files/1081676/main.zip)

**Comment by Hotsotse** [comment]
Not sure how to grant access to push but I've added you as a collaborator. Thank you for the contribution!
